open_system('ld3_fixed_point2');
open_system('gm_ld3_fixed_point2');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ld3_fixed_point2/IIR/Delay', 'user1');
hilite_system('ld3_fixed_point2/IIR/Delay', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ld3_fixed_point2/IIR/Delay1', 'user1');
hilite_system('ld3_fixed_point2/IIR/Delay1', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ld3_fixed_point2/IIR/Subtract1', 'user1');
hilite_system('ld3_fixed_point2/IIR/Subtract1', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ld3_fixed_point2/IIR/Subtract2', 'user1');
hilite_system('ld3_fixed_point2/IIR/Subtract2', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ld3_fixed_point2/IIR/a(2)', 'user1');
hilite_system('ld3_fixed_point2/IIR/a(2)', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ld3_fixed_point2/IIR/a(3)', 'user1');
hilite_system('ld3_fixed_point2/IIR/a(3)', 'user1');
